/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PatternRandomizerRouteImport } from './routes/pattern-randomizer'
import { Route as IndexRouteImport } from './routes/index'

const PatternRandomizerRoute = PatternRandomizerRouteImport.update({
  id: '/pattern-randomizer',
  path: '/pattern-randomizer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pattern-randomizer': typeof PatternRandomizerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pattern-randomizer': typeof PatternRandomizerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pattern-randomizer': typeof PatternRandomizerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pattern-randomizer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pattern-randomizer'
  id: '__root__' | '/' | '/pattern-randomizer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PatternRandomizerRoute: typeof PatternRandomizerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pattern-randomizer': {
      id: '/pattern-randomizer'
      path: '/pattern-randomizer'
      fullPath: '/pattern-randomizer'
      preLoaderRoute: typeof PatternRandomizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PatternRandomizerRoute: PatternRandomizerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
